### ISSUE TITLE
Does this only work with Google/DDG?

### ISSUE THREAD

**Issue by MintMain21** [igorlogius/searchpreview-overload#1]
Cause I know one othet extension (https://addons.mozilla.org/firefox/addon/search_result_previews/) that also supports Startpage, Ecosia, and Brave.

**Comment by igorlogius** [comment]
Hi @MintMain21,

i planned to add more search engines, but currently it only works with Google and DDG. 

Unfortunately Juraj's addon does not seem to be open source, so i can't take a look at his implementation to more quickly get feature parity. 

Since you are the first one asking, which one would be of most interest to you?

**Comment by MintMain21** [comment]
Well the above three I mentioned (Brave, Ecosia, and Startpage) are the three I would most value (my default is DDG). 

After that, maybe something like Swisscows?

**Comment by igorlogius** [comment]
Thank your for the feedback. 

Please open an individual issue (feature request) for each search engine you'd like support for. 

That will help me keep things organized and trackable. :) 

PS: 
Since your inital title question has been answered, i'll close this issue.
